### ISSUE TITLE
Resources fail to install 

### ISSUE THREAD

**Issue by ih8legal** [Aspire0ne/Google-Assistant-enabler#4] opened 2020-08-21 20:32 UTC
Resources appear to download rather quickly, but don't install. I installed the resources apk manually, and muted the lines of code to install them. Now it appears to be working.

**Comment by AspireOne** [comment] 2020-08-21 20:57
How quickly does it download? What's your normal downloading speed? Does it throw an error that it can't install it or does it just silently fail?

**Comment by ih8legal** [comment] 2020-08-21 20:59
It downloads almost instantly, it does give an error, unable to install. Then shorts installation of the module

**Comment by AspireOne** [comment] 2020-08-21 21:17
Does it gradually increase percentage during downloading or does it directly skip to 100%?

**Comment by ih8legal** [comment] 2020-08-21 21:19
It happens almost instantly, hard to tell.

**Comment by AspireOne** [comment] 2020-08-21 21:32
It shows the percentage in the Magisk Manager console, doesn't it?

**Comment by ih8legal** [comment] 2020-08-21 21:34
Let me run it again and I'll take a screenshot.

**Comment by ih8legal** [comment] 2020-08-21 22:10
![Screenshot_20200821-144249](https://user-images.githubusercontent.com/18506928/90939411-81417c80-e3c0-11ea-903e-24fb43d4503a.jpg)

**Comment by ih8legal** [comment] 2020-08-21 22:11
This happens almost instantly

**Comment by AspireOne** [comment] 2020-08-21 22:33
I see... I suppose there is either a problem with some mediafire protection (although it works for me), or with the link itself. I'll try to upload the file on a different hosting server, I believe that that should fix it. May you please test it out when you have time after I upload it? I will have it ready today or tomorrow, I would let you know.

**Comment by ih8legal** [comment] 2020-08-21 22:41
You could just include the download in the module, they have to download it anyway. I can help you test, although I'm having other issues that prevent me from keeping it installed. There's already another issue open for it. The Google app keeps force closing when trying to search in the bar, as others said, it's because of the email in the xml file, when I change it to my own email, it doesn't crash anymore, but assistant doesn't work correctly and eventually there's no more UI at all.

**Comment by AspireOne** [comment] 2020-08-22 02:42
I know about the search bar crashes caused by gmail in GSAPrefs, but sadly, I haven't found a way to fix it (yet).

The resources **were** initially included with the module, but I couldn't host it on github because it's file size limit is 25mb (and the file had ~140mb) so I decided to let it download what it needs.

Anyways I decided to pack the resources with the module, which means that the binaries will be hosted elsewhere from now on, but code and releases will stay here on github (without the resources).

That solves the downloading problem so I'm closing this issue. Thank you for the feedback.

**Closed as completed by AspireOne** 2020-08-22 02:42 UTC
Labels: bug
